"""
reports/csv_report.py — CSV Report Generator for AI Resume Analyzer Pro
========================================================================
Generates a structured CSV report containing student information,
ATS score, skills analysis, and internship match results.
"""

import csv
import io
from datetime import datetime
from typing import Any, Dict, List, Optional


def generate_csv_report(
    student_name: str,
    email: str,
    ats_score: float,
    skills_found: List[str],
    missing_skills: List[str],
    internship_matches: List[Dict[str, Any]],
) -> str:
    """
    Build a multi-section CSV report and return its content as a string.

    Sections
    --------
    1. **Student Info** — name, email, report date
    2. **ATS Score** — overall score
    3. **Skills Found** — one skill per row
    4. **Missing Skills** — one skill per row
    5. **Internship Matches** — title, match %, and category

    Parameters
    ----------
    student_name : str
        Full name of the student.
    email : str
        Student email address.
    ats_score : float
        Computed ATS compatibility score (0-100).
    skills_found : list[str]
        Skills detected in the resume.
    missing_skills : list[str]
        Recommended skills the resume is lacking.
    internship_matches : list[dict]
        Each dict should contain at least ``title``, ``match_percentage``,
        and optionally ``category``.

    Returns
    -------
    str
        The full CSV content ready to be downloaded or written to a file.
    """
    output = io.StringIO()
    writer = csv.writer(output)
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── Section 1: Student Information ─────────────────────────────────
    writer.writerow(["=== STUDENT INFORMATION ==="])
    writer.writerow(["Field", "Value"])
    writer.writerow(["Name", student_name])
    writer.writerow(["Email", email])
    writer.writerow(["Report Date", report_date])
    writer.writerow([])  # blank separator

    # ── Section 2: ATS Score ───────────────────────────────────────────
    writer.writerow(["=== ATS SCORE ==="])
    writer.writerow(["Metric", "Value"])
    writer.writerow(["Overall ATS Score", f"{ats_score:.1f}%"])
    writer.writerow([])

    # ── Section 3: Skills Found ────────────────────────────────────────
    writer.writerow(["=== SKILLS FOUND ==="])
    writer.writerow(["#", "Skill"])
    if skills_found:
        for idx, skill in enumerate(skills_found, start=1):
            writer.writerow([idx, skill])
    else:
        writer.writerow(["-", "No skills detected"])
    writer.writerow([])

    # ── Section 4: Missing / Recommended Skills ────────────────────────
    writer.writerow(["=== MISSING / RECOMMENDED SKILLS ==="])
    writer.writerow(["#", "Skill"])
    if missing_skills:
        for idx, skill in enumerate(missing_skills, start=1):
            writer.writerow([idx, skill])
    else:
        writer.writerow(["-", "No gaps identified"])
    writer.writerow([])

    # ── Section 5: Internship Matches ──────────────────────────────────
    writer.writerow(["=== INTERNSHIP MATCHES ==="])
    writer.writerow(["#", "Title", "Match %", "Category"])
    if internship_matches:
        for idx, match in enumerate(internship_matches, start=1):
            title = match.get("title", "N/A")
            pct = match.get("match_percentage", 0)
            category = match.get("category", "N/A")
            writer.writerow([idx, title, f"{pct:.1f}%", category])
    else:
        writer.writerow(["-", "No matches found", "-", "-"])

    # ── Footer ─────────────────────────────────────────────────────────
    writer.writerow([])
    writer.writerow(["Generated by AI Resume Analyzer Pro"])
    writer.writerow(["Report Date", report_date])

    return output.getvalue()
